### ISSUE TITLE
Incorrect snakemake installation

### ISSUE THREAD

**Issue by hummuscience** [crazyhottommy/pyflow_seuratv3_parameter#1]
You have a typo here:
`conda create n=snakemake python=3.6 snakemake
`

should be:

`conda create -n snakemake python=3.6 snakemake
`
but that doesn't work since snakemake needs to be installed from bioconda. So the current suggestion is to create the environment with mamba.

```
conda install -c conda-forge mamba
mamba create -c conda-forge -c bioconda -n snakemake snakemake
```

https://snakemake.readthedocs.io/en/stable/getting_started/installation.html

**Comment by crazyhottommy** [comment]
Thanks! I just updated the README. I plan to add more README in the future.
