### ISSUE TITLE
Running snakemake on a local workstation

### ISSUE THREAD

**Issue by Jay-Leung** [crazyhottommy/pyflow_seuratv3_parameter#10]
Hello! I understand that the snakemake workflow is usually run on a hpc due to the high CPU requirement. However, I would like to run this on a local workstation and would like to check if this is possible. The specifications of the workstation are 16 cores, 32 threads with about 100GB RAM. I am looking to run this on a ~5GB Seurat object with varying parameters of 5 varying PCs, 5 k-params, and 5 resolutions, Could I check if this can be run in this case? Thanks!

**Comment by JSLJ23** [comment]
Dear Ming Tang,

I am helping Jay with setting up and running this snakemake workflow on a local workstation.
I have installed R with Seurat and SeuratOjbect packages and when I run the snakemake file with the --use-singularity argument, I still run into the error below:

Loading required package: SeuratObject
Error in .requirePackage(package) : 
  unable to find required package ‘SeuratObject’
Calls: eval ... .extendsForS3 -> extends -> getClassDef -> .requirePackage
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘SeuratObject’
Execution halted

May I know how do I go about rectifying this?
Thanks.

**Comment by crazyhottommy** [comment]
Hi, SCTransform uses a lot of memory, I recommend running the snakemake workflow in a cluster. I just helped someone and they had it run successfully. 
@JSLJ23 the singularity is only for Seurat V3, if you use Seurat V4, you will need to install `Seurat` and `tidyverse` on your HPC and then run  snakemake without specifying --singularity. I mentioned that in the README.
if you use slurm you can use `./pyflow-scBoot.sh` and change  https://github.com/crazyhottommy/pyflow_seurat_parameter/blob/master/cluster.json for memory and time request for your dataset.

**Comment by Jay-Leung** [comment]
Dear Ming Tang,

Sadly we don't have easy access to a HPC. We understand that SCTransform takes up a lot of RAM, so when we ran 5 jobs it ran into errors, likely due to insufficient memory. Would it be possible to limit the number of cores, say 3, such that the jobs are ran serially instead of parallelizing the workflow? Do you have an idea of the rough memory needed for 1 job on say a 1.5GB Seurat Object? Thanks!

**Comment by crazyhottommy** [comment]
yes, you can run `snakemake -j 3`. I have not tried SCTransform myself. you may run it interactively and check the memory usage.

**Comment by Jay-Leung** [comment]
Hi Ming Tang, 

We have gotten it to work by limiting the jobs. I have an additional question - for FindClusters, is the Louvain/Leiden algorithm being used? 

Also, I see that the general trend is that the number of stable clusters increases when I increase k-params to 100, which makes sense because it's less clusters and a more global outlook. But from the datasets you have used, it seems like you have selected a small k-params for visualisation. Is there a reason why you didn't go for k = 100 with better Jaccard scores? I also realised there is a slight discrepancy - the sihouette width scores in general do not look quite as good as Jaccard scores, which I see in your visualisations as well. If you are using the conventional way of calculating silhouette scores, shouldn't the silhouette scores be comfortably more than zero to ensure the clustering quality is okay? 

Thanks a lot for this package!

**Comment by crazyhottommy** [comment]
Yes, Louvain/Leiden algorithm is used as default in Seurat. 
when you increase K, the fewer clusters you will have.
The way to select the k, pc number and resolution is to make sure you get the more stable clusters at the same time most of the cells are in the stable clusters.

Silhouette width is calculated for each cell, the jaccard is calculated for each subsampling. Both of them measures the stability of the clusters but different too.

**Comment by crazyhottommy** [comment]
Let me know if you still have questions. closing it for now.

**Comment by JSLJ23** [comment]
Dear Ming Tang,

Yes this has been resolved.
Thank you so much for your help and for creating this tool.

Regards,
Joshua Soon

**Comment by crazyhottommy** [comment]
Glad it worked for you!
