### ISSUE TITLE
The order of script I should run

### ISSUE THREAD

**Issue by Paria06** [crazyhottommy/pyflow_seuratv3_parameter#12]
Dear Ming,
I'm trying to do subsampling. But the workflow is not quite clear to me. I have a couple questions:
First, what is snakemake in log <- file(snakemake@log[[1]], open="wt")
Second, in which order I should run the script in R and before running pyflow-scBoot.sh. 
Thanks,
Paria

**Comment by crazyhottommy** [comment]
"log <- file(snakemake@log[[1]], open="wt")" is just for logging the errors.

You should have a fully processed Seurat object. `pyflow-scBoot.sh` is only for Slurm on HPC.

**Comment by Paria06** [comment]
I mean when I run "log <- file(snakemake@log[[1]], open="wt")" I got the error that there is no snakemake object. To what value I should assign snakemake? and after processing the samples by running "preprocess.R > subsample.R > gather_subsample.R > gather_fullsample.R" in r I should run pyflow-scBoot.sh? Actually I'm using Slurm on HPC.
Thanks,
Paria

**Comment by crazyhottommy** [comment]
you do not run "log <- file(snakemake@log[[1]], open="wt")" interactively in R. You should run the Snakemake workflow.

You should just run pyflow-scBoot.sh directly and give the seurat object name in the config.ymal

**Comment by Paria06** [comment]
Thanks for your swift response. I did try it. I added integrated Seurat object and dimensionally reduced to pyflow_seurat_parameter folder. when I run pyflow-scBoot.sh (removing --use-singularrity) I'm getting the below error:
sbatch: error: ----------------------------------------
sbatch: error: The specified partition does not exist, or the submitted job cannot fit in it...
sbatch: error: Please specify a different partition, or simply submit the job without the --partition option,
sbatch: error: the scheduler will redirect it to the most suitable partition automatically
sbatch: error: ----------------------------------------
sbatch: error: Batch job submission failed: Unspecified error

when I remove the --partition {cluster.p} I'm still getting an error. I appreciate your help on this
Paria

**Comment by crazyhottommy** [comment]
every slurm has different partition names, you should change https://github.com/crazyhottommy/pyflow_seurat_parameter/blob/master/cluster.json#L8 according to your HPC

**Comment by Paria06** [comment]
Oh, okay. I had no idea that I need to change this. Do you know how could I get this info?
Thanks,
Paria

**Comment by crazyhottommy** [comment]
you will have to ask the HPC team in your school.  this is from Harvard RC https://docs.rc.fas.harvard.edu/kb/running-jobs/#Slurm_partitions, but different HPC has different settings

**Comment by Paria06** [comment]
Okay, thank you so much for your help!

**Comment by Paria06** [comment]
I have one more question. I did run it successfully and get the folders including subsample.rds & fullsample.rds but not gather_subsample.rds & gather_fullsample.rds. I don't see any log for it. As I'm not using singularity should I change singularity: "docker://crazyhottommy/seuratv3" in Snakefile?
Thank you!

**Comment by crazyhottommy** [comment]
Are you sure the workflow finished successfully? 
you should have 
`subsample/subsample_k_{k}_resolution_{resolution}_PC_{pc}_round_{run_id}.rds`
and `full_sample_preprocess/full_sample_k_{k}_resolution_{resolution}_PC_{pc}.rds` in your folder
for all the combinations of k, pc and resolution. and the max {run_id} should be the number of subsampling.

simply rerun the snakemake will only run the ones that have not run.

**Comment by Paria06** [comment]
Yeah, I'm sure. Sounds good. I'll rerun it.
Thanks a lot
