### ISSUE TITLE
Error when running snakemake

### ISSUE THREAD

**Issue by hummuscience** [crazyhottommy/pyflow_seuratv3_parameter#2]
Sooo, I tried the workflow as it is and realized that for some reason it takes up all my RAM when running a single job with a 5Gb (50k cells) dataset.

I then had a look in the code and saw that you run SCTransform on the data, which is probably why it chokes in my situation. 

So I went on to comment out the lines where you normalize and scale the data since all of this is already done in my seurat object (and probably should be option, since many people already did normalization).

Ran it then with 5 jobs and saw that my RAM is not filling up but it still quit with an error:

```
RuleException:
CalledProcessError in line 41 of /home/generalubuntu/repos/pyflow_seuratv3_parameter/Snakefile:
Command 'set -eo pipefail; echo BEGIN at $(date);  Rscript --vanilla /home/generalubuntu/repos/pyflow_seuratv3_parameter/.snakemake/scripts/tmpzcw704wr.preprocess.R ; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat' returned non-zero exit status 1.
  File "/home/generalubuntu/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2189, in run_wrapper
  File "/home/generalubuntu/repos/pyflow_seuratv3_parameter/Snakefile", line 41, in __rule_full_sample_preprocess
  File "/home/generalubuntu/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 529, in _callback
  File "/home/generalubuntu/anaconda3/envs/snakemake/lib/python3.7/concurrent/futures/thread.py", line 57, in run
  File "/home/generalubuntu/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 515, in cached_or_run
  File "/home/generalubuntu/anaconda3/envs/snakemake/lib/python3.7/site-packages/snakemake/executors/__init__.py", line 2201, in run_wrapper

```

**Comment by crazyhottommy** [comment]
Hi,
You are right, SCTransform takes a lot of RAM. you can either use a big RAM HPC or change the R script to use the old Seurat processing workflow: `NormalizeData`, `ScaleData` and `FindVariableFeatures`. 
Do you see anything in the log file? `log: "00log/full_sample_k_{k}_resolution_{resolution}_PC_{pc}.log"` also are you using `singularity` or you installed Seurat yourself?

**Comment by hummuscience** [comment]
I found the problem, I had to set `DefaultAssay(object) <- "RNA"` since my object also contained SCT without dimensionality reduction.

Basically these bugs have nothing to do with your code and rather with my changes.

I am basically skipping the normalization and PCA completely and passing my own dimensionality reduction myself.

**Comment by crazyhottommy** [comment]
I should make the pipeline more flexible to accommodate different usages.

**Comment by crazyhottommy** [comment]
btw, for the sub-sampled the dataset, you probably still want to do `SCtransform` at https://github.com/crazyhottommy/pyflow_seuratv3_parameter/blob/master/scripts/subsample.R#L52  but skip it for the full dataset (comment out) at https://github.com/crazyhottommy/pyflow_seuratv3_parameter/blob/master/scripts/preprocess.R#L35
