### ISSUE TITLE
How to run workflow on multiple PCs?

### ISSUE THREAD

**Issue by hummuscience** [crazyhottommy/pyflow_seuratv3_parameter#3]
The workflow is working now. so thank you!

However, I noticed that the workflow only worked using the number of PCs that I set manually (20) in the config.yaml file and did not try multiple PCs. From your examples of the analysis, it seems like you can run it on multiple PCs. 

Where do I have to set this option?

**Comment by crazyhottommy** [comment]
great! you can set up https://github.com/crazyhottommy/pyflow_seuratv3_parameter/blob/master/config.yaml#L17 
specify multiple numbers separated by space (number of PCs to use).

Note, `num.pc`(the number of PC to calculate)  in https://github.com/crazyhottommy/pyflow_seuratv3_parameter/blob/master/config.yaml#L31 should be greater than every entry in the `subsample_pcs`.

After you specify multiple PCs in the config.yaml file, you just re-run Snakemake, and the results for other PCs will be added, no need to remove the previous calculated single PC result.
