### ISSUE TITLE
Cannot allocate vector error 

### ISSUE THREAD

**Issue by aditisk** [crazyhottommy/pyflow_seuratv3_parameter#4]
Hi @crazyhottommy, I'm running into memory issues while working with a large Seurat object (~130k cells). I tested the pipeline on a smaller object (~30k cells) and it works fine. 

This is the error I'm getting:

Error: cannot allocate vector of size 25.3 Gb
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
Warning message:
system call failed: Cannot allocate memory

I'm running this on our HPC cluster. I am using Singularity to pull the Seurat image. It looks like an R memory issue but I'm not sure how to fix it. Have you faced a similar issue before with a large number of cells ? How did you fix it ? Thanks.

**Comment by crazyhottommy** [comment]
Hi @aditisk , it has to do with `SCTransform` in Seurat. it requires a lot of memory for a big dataset. check https://github.com/crazyhottommy/pyflow_seuratv3_parameter/issues/2

you can change the code at https://github.com/crazyhottommy/pyflow_seuratv3_parameter/blob/master/scripts/preprocess.R#L35

and https://github.com/crazyhottommy/pyflow_seuratv3_parameter/blob/master/scripts/subsample.R

for `PreprocessSubsetData` function

**Comment by aditisk** [comment]
Hi @crazyhottommy, thanks for the suggestion. I'll give it a try.

**Comment by aditisk** [comment]
Hi @crazyhottommy, I commented out the SCTransform() and RunPCA() lines from the code and re-ran the workflow. My screen session showed this message and froze:

[Sat Jun 27 16:28:59 2020]
Job 501: gathering idents for subsample k

Activating singularity image /zfs1/rferris/adk85/Tools/scclustereval/pyflow_seuratv3_parameter/.snakemake/singularity/8773defce32c345ee6f0a445dcf11ba1.simg

I'm attaching the full log file here. I ended the workflow since it seemed to be frozen (no jobs were queued or running for sometime). I see 2 RDS files being created. What should I do to ensure a successful completion of the workflow ? 

[2020-06-27T123018.906416.snakemake.log](https://github.com/crazyhottommy/pyflow_seuratv3_parameter/files/4841230/2020-06-27T123018.906416.snakemake.log)

**Comment by crazyhottommy** [comment]
according to the log, it seems it run successfully. 
do you see `gather_subsample.rds` and `gather_full_sample.rds` and can you load those two into R?

take a look at this again, I replied https://github.com/crazyhottommy/pyflow_seuratv3_parameter/issues/2

**Comment by aditisk** [comment]
I was able to load those 2 object in R. Thanks for the comment in #2 I'll repeat it according to that.

Would you recommend running this analysis on each broad cell type (immune cells, stroma etc. one at a time) or all the cells together ? I was wondering if having very different cell types will skew the results.

Thanks once again for your prompt responses and help with this.

**Comment by crazyhottommy** [comment]
I would suggest running for all the cell first. and if you want to find stable sub-clusters, you can subset the Seurat object and run the analysis on specific cells (CD8+ cells).
