### ISSUE TITLE
Error in running snakemake pipeline

### ISSUE THREAD

**Issue by mthimma** [crazyhottommy/pyflow_seuratv3_parameter#7]
Hi,

I am facing error while running snakemake on a seurat object created using Seurat v4.0

00log/full_sample_k_8_resolution_1.4_PC_150.log
Loading required package: SeuratObject
Error in .requirePackage(package) : 
  unable to find required package ‘SeuratObject’
Calls: eval ... .extendsForS3 -> extends -> getClassDef -> .requirePackage
In addition: Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘SeuratObject’
Execution halted

My current folder looks like this.

>~/bioinformatics_tools/pyflow_seuratv3_parameter$ ls
00log  cluster.json  config.yaml  envs  LICENSE  pyflow-scBoot.sh  README.md  scripts  seurat_obj.rds  Snakefile

Could you please help me sort out this.

**Comment by crazyhottommy** [comment]
Hi, Currently, the snakemake workflow is not compatible with Seurat V4. https://github.com/crazyhottommy/pyflow_seuratv3_parameter/issues/6
We are working on that and will update you here.

**Comment by crazyhottommy** [comment]
Hi @mthimma. Scott just made a PR to support Seurat V4 SCTransform, can you try it out?  and you need to install SeuratObject package yourself.

**Comment by mthimma** [comment]
What is this SeuratObject package? Is this any python package?
I have R and Seurat installed in my workstation.

**Comment by mthimma** [comment]
Also, I did install snakemake about 5 days ago. If you have updated after that let me try to download and install snakemake again.

**Comment by crazyhottommy** [comment]
It is an R package. https://cran.r-project.org/web/packages/SeuratObject/SeuratObject.pdf

**Comment by crazyhottommy** [comment]
Let me know if you are able to run it or not
