### ISSUE TITLE
Error in Snakefile

### ISSUE THREAD

**Issue by daccachejoe** [crazyhottommy/pyflow_seuratv3_parameter#9]
Hi - I just installed snakemake and your package and am new to this so I apologize if the question is mundane. I tried dry running snakemake after installation and I obtained this error in regards to the SnakeFile in the pyflow directory. Any idea as to what is causing this error?

Thanks for your help!

`SyntaxError in line 36 of /home/daccache/pyflow_seurat_parameter/Snakefile:
Unexpected keyword singularity in rule definition (Snakefile, line 36)`

**Comment by crazyhottommy** [comment]
it seems the most recent version of snakemake changed singularity to container: https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html#singularity

you can use an old version of Snakemake or change the "singularity" in the Snakefile to "container"

**Comment by daccachejoe** [comment]
Hi- thanks for your quick response. Unfortunately I don't think modifying the Snakefile worked for me. I tried doing so and it caused the same error, except this time with "container" and not "singularity". thoughts on how to move forward from here?
Thanks!

`$snakemake -np
SyntaxError in line 36 of /home/daccache/pyflow_seurat_parameter/Snakefile:
Unexpected keyword container in rule definition (Snakefile, line 36)
`

**Comment by crazyhottommy** [comment]
can you use an earlier version of Snakemake? I have not tested it for the newest version.

**Comment by daccachejoe** [comment]
Yes I can try, what version should I install? From Snakemake's [ Change Log](https://snakemake.readthedocs.io/en/stable/project_info/history.html) it says the changes are in 6.3.0 but the most recent Snakemake version (as seen by conda list in my enviroment with the newest one installed) is 3.13.3. Sorry for the dumb question here but where could I find out what the last version number is?

Update: Successfully installed versions 3.12 and 3.11 but both called the same error in regards to "singularity"

**Comment by crazyhottommy** [comment]
it should be before 5.11.0 https://snakemake.readthedocs.io/en/stable/project_info/history.html#id106

3.11 and 3.12 seem to be too old. they may not support singularity at that time.

on my computer.
```
snakemake --version
5.14.0
```

**Comment by jad362** [comment]
Hi thanks again for your reply. I had to work out a solution with my HPC team which complicated the installation procedure but I am now set up. Unfortunately, when I run the pipeline, I run into this error
`/usr/bin/bash: line 1:  3770 Killed                  Rscript --vanilla /home/daccache/pyflow_seurat_parameter/.snakemake/scripts/tmp4s49vwx2.preprocess.R
[Fri Apr 30 15:59:04 2021]
Error in rule full_sample_preprocess:
    jobid: 456
    output: full_sample_preprocess/full_sample_k_10_resolution_0.5_PC_50.rds
    log: 00log/full_sample_k_10_resolution_0.5_PC_50.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 41 of /home/daccache/pyflow_seurat_parameter/Snakefile:
Command 'set -eo pipefail; echo BEGIN at $(date);  Rscript --vanilla /home/daccache/pyflow_seurat_parameter/.snakemake/scripts/tmp4s49vwx2.preprocess.R ; exitstat=$?; echo END at $(date); echo exit status was $exitstat; exit $exitstat' returned non-zero exit status 137.
  File "/home/daccache/pyflow_seurat_parameter/Snakefile", line 41, in __rule_full_sample_preprocess
  File "/apps/prod/easybuild/sl7.x86_64/software/Python/3.6.3-foss-2017b/lib/python3.6/concurrent/futures/thread.py", line 56, in run
`

Do you know what is causing this?

Thanks for your help!

**Comment by daccachejoe** [comment]
Hi thanks again for your reply. I had to work out a solution with my HPC team which complicated the installation procedure but I am now set up. Unfortunately, when I run the pipeline, I run into the classic error that references line 41 of SnakeFile (the Rscript line). Then it says `/bib/bash: line 1" 212241 Killed Rscript --vanilla /home/daccache/pyflow_seurat_parameter/.snakemake/scripts/tmpczi14lwk.preprocess.R` When I check the error logs in 00log/ there is no R error present and every object just has a log file that has the expected Seurat verbose output in it from NormalizeData (I have too many cells to use SCTransform).

So this seems like a memory issue on the HPC server but I have 120 cores and 400GB available to me and the error message I am receiving is not a scheduler killing my job. I've run snakemake -j with numbers 120 and lower, but the error always occurs. Then I tried decreasing the-j # to 15 (the number of simultaneous pipelines) and then using the future multiprocessing within R but that also failed.

Am I misunderstanding something about the memory allocation process here? How can I ensure the pipeline not only runs but does so with all the resources available to me?

Thanks!

**Comment by crazyhottommy** [comment]
if you do not use SCTransform, use https://github.com/crazyhottommy/pyflow_seurat_parameter/releases/tag/v0.1 for SeuratV3. it has a Seurat V3 singularity image to use.
if you use SCTransform, use https://github.com/crazyhottommy/pyflow_seurat_parameter/releases/tag/v1.0 I have not made a Seurat V4 singularity image, so you will need to install Seurat V4 yourself and do not use `--use-singularity` flag.
I am aware that SCTransform needs a lot of memory for big data.

**Comment by daccachejoe** [comment]
Hi- sorry I think I might be confused here. The error I'm receiving is not an R error or due to SCTransform (I wrote in the normal Normalize --> Scale --> FindVariableFeatures pipeline). I think this because the R logs (the logs in the 00log/ directory) have no error messages. The screen just prints this error message 
`/bin/bash: line 1: 24978 Killed                  Rscript --vanilla /home/daccache/pyflow_seurat_parameter/.snakemake/scripts/tmpf05878co.preprocess.R`
and the corresponding R log would have an incomplete progress bar like this and nothing else:

Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Regressing out percent.mt, nFeature_RNA
  |======                                                                |   8%

For reference, this is only happening in some of the objects being preprocessed and not all of them. Have you encountered this before? Thanks

**Comment by crazyhottommy** [comment]
Hi,
So you are able to at least get some results? I am not sure what's wrong here.
I would suggest you to run 

```
snakemake --rerun-incomplete
```
to just recreate that object and see if that error persists or not.

**Comment by daccachejoe** [comment]
Hi thanks - I just ran with the 'rerun-incomplete' tag but the pipeline went straight to the subsampling rather than reprocessing the incomplete preprocessed objects which induced an error since nCells could not exist. Since I am just as confused here I've included three log files for reference
1. [Master Log](https://github.com/crazyhottommy/pyflow_seurat_parameter/files/6420806/2021-04-30T155404.559439.snakemake.log)
2. [Completed object job](https://github.com/crazyhottommy/pyflow_seurat_parameter/files/6420792/full_sample_k_12_resolution_1.5_PC_50.log) - on object which successfully went through preprocess.R
3. [Incomplete object log](https://github.com/crazyhottommy/pyflow_seurat_parameter/files/6420801/full_sample_k_8_resolution_0.5_PC_50.log) - an object that had the bin/bash line 1 killed error code

Here is my full_sample_preprocess directory, there are currently 6 objects out of the 15 expected (given all combinations of k's and resolutions inputted). Is there a way for me to rerun preprocess.R only the objects that are not present here?
├── full_sample_preprocess
│   ├── full_sample_k_12_resolution_1.5_PC_50.rds
│   ├── full_sample_k_14_resolution_0.5_PC_50.rds
│   ├── full_sample_k_14_resolution_1.5_PC_50.rds
│   ├── full_sample_k_16_resolution_1_PC_50.rds
│   ├── full_sample_k_8_resolution_1.5_PC_50.rds
│   └── full_sample_k_8_resolution_1_PC_50.rds


Thanks again for your help

**Comment by crazyhottommy** [comment]
Hi,
You can do 
```
snakemake --until gather_full_sample_preprocess
```
It will only re-run for the ones that failed. I want to know if the same one always failed or it is kind of random?

**Comment by daccachejoe** [comment]
Thanks for that option flag, big help and it seems to be working now. 

To answer your question about which objects were failing, I reran the entire pipeline and the below objects are what were processed successfully the first time. By rerunning the subsequent pipelines with `--until gather_full_sample_preprocess`  flagged, the other objects all were successfully preprocessed.

├── full_sample_preprocess
│   ├── full_sample_k_12_resolution_0.5_PC_50.rds
│   ├── full_sample_k_12_resolution_1_PC_50.rds
│   ├── full_sample_k_16_resolution_1_PC_50.rds
│   ├── full_sample_k_20_resolution_0.5_PC_50.rds
│   ├── full_sample_k_20_resolution_1.5_PC_50.rds
│   └── full_sample_k_20_resolution_1_PC_50.rds

Moving forward, I've processed the subsamples once and the same, bash-related, memory error was being flagged for some of the objects but not all of them so now I am running it with restart times since I know the errors are memory related and can be reperformed (as opposed to one due to the underlying code which would always produce an error no matter how many times it tries to perform it). `snakemake -j 100 --restart-times 5 --until gather_subsample` Do you know how I can tell snakemake to wait x seconds before trying to restart a job?

**Comment by crazyhottommy** [comment]
I think `--wait-latency` ? glad to know it is working for you.

**Comment by daccachejoe** [comment]
yes, it was `--latency-wait`

Thanks for your help on this by the way, it all processed successfully. I appreciate your help!

**Comment by crazyhottommy** [comment]
great!
